### ISSUE TITLE
Jira cloud account asked for new password

### ISSUE THREAD

**Issue by plaidshirtakos** [katalon-studio-samples/katalon-bdd-cucumber-tests#1]
Microsoft account (demo@katalon.com) asked for new password, when I tried to login with provided credentials. I set **DontKnow2018** as password.

**Comment by trongbui** [comment]
This is the account used by all the sample projects and other users. Any update can cause issue to the community. Pls be careful.

**Comment by devalex88** [comment]
@plaidshirtakos,

Thank you so much for the heads-up. This is due to changes in Microsoft's password policy. We've updated the password accordingly.
