### ISSUE TITLE
should include example for Cucumber/Ruby combination

### ISSUE THREAD

**Issue by rpjesivac** [katalon-studio-samples/katalon-bdd-cucumber-tests#2]
official documentation states that "Step Definitions can be written in any Cucumber-supported programming languages including Groovy and Java." but it is not clear how to do that for languages that is not Java.

Since Ruby is the most frequently used with Cucumber it would be great to add an example code for that

**Comment by trongbui** [comment]
Thank you for your suggestion. Cucumber and Ruby is a famous combo and I also use them for some years. Unfortunately, Katalon Studio has not supported Ruby yet, might be in the near future but not at the moment. 

Hope that you could find the example helpful with Java and Groovy used in Katalon Studio.
